### ISSUE TITLE
Crash on Mac when adding stream

### ISSUE THREAD

**Issue by botronic** [kaszim/desktop-stream-viewer#131]
Error: "File "/Users/botronic/desktop-stream-viewer/vlc.py", line 270, in _Cfunction
    raise NameError('no function %r' % (name,))
NameError: no function 'libvlc_media_new_callbacks'"

**Comment by mictab** [comment]
Can't reproduce.

Are you doing this using the latest master?

Have you followed the instructions for macOS at https://github.com/kaszim/desktop-stream-viewer/blob/master/docs/setup_macos.md ?

**Comment by mictab** [comment]
Fixed.
