### ISSUE TITLE
Two BUGS in Import Recent Session

### ISSUE THREAD

**Issue by MDinler** [kaszim/desktop-stream-viewer#148]
1. When adding a new stream to the current session and then pressing "Import Recent Session" will load the stream that was added in the current session. That is, if I had two streams (X and Y) running last session and start a new session by adding stream Z before Importing Recent Session, I will end up with four streams (Z, X, Y and Z).

2. Import Recent Session does not import the streams from latest session. It seems to open every stream that has been opened  thus far

**Comment by MDinler** [comment]
Maybe bug 1 and 2 is the same bug?

**Comment by mictab** [comment]
Are you talking about the functionality introduced in https://github.com/kaszim/desktop-stream-viewer/pull/102/ ?

**Comment by MDinler** [comment]
Yes
