### ISSUE TITLE
Test the Streamlink plugns

### ISSUE THREAD

**Issue by svenanderzen** [kaszim/desktop-stream-viewer#47]
The following plugins should be tested that they work properly. 
- [x] Twitch
- [x] Hitbox
- [x] Azubu
- [x] MLG
- [x] Dailymotion
- [x] DIngit
- [x] Douyu
- [x] Huomao
- [x] Stream.me
- [x] Youtube

**Comment by mictab** [comment]
Have these been tested?

**Comment by mictab** [comment]
Woho.
