### ISSUE TITLE
Remove stream?

### ISSUE THREAD

**Issue by svenanderzen** [kaszim/desktop-stream-viewer#95]
I see some functions to remove the stream but I can't find it implemented anywhere in the UI? Perhaps it's just me that can't find it or have we not implemented this yet? 

Perhaps you could shed some light? @botronic

**Comment by kaszim** [comment]
Yeah it is not bound to anything currently. Ping @MDinler @jaokob get that button ready.

If you want to try the functionality you can rebind the toolbox to remove stream.

**Comment by botronic** [comment]
That is how I did it hehe
